version: '3'

services:
  server:
    image: "dfkozlov/junction-ericsson-5g_master:latest"
    ports:
      - 8000:8000
      - 8080:8080
    network_mode: "host"

  client:
    image: "dfkozlov/junction-ericsson-5g_master:latest"
    command: bash /root/start.sh
    network_mode: "host"

  #ui:
  #  image: "${IMAGE}"
  #  command: bundle exec thin -p 3000
  #  network_mode: "host"
