version: '3'

services:
  server:
    image: "{{image_name}}"
    command: sudo /opt/city/citysim -config /opt/city/server2/game-config.json -map-dir /root/custom_maps
    ports:
      - 8000:8000
      - 8080:8080
    network_mode: "host"

  client:
    image: "{{image_name}}"
    command: bash /root/start.sh
    network_mode: "host"

  #ui:
  #  image: "${IMAGE}"
  #  command: bundle exec thin -p 3000
  #  network_mode: "host"
