- hosts: localhost
  connection: local
  vars_files:
    - ../vars-files/default.yml
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  pre_tasks:
    - debug:
        msg: "{{ hostvars }}"
  roles:
    - { role: api-tests }
